#!/usr/bin/env python3

import argparse
import re
#from Bio.Blast.Applications import NcbiblastnCommandline
from Bio import SeqIO
import sys
import shutil
import pandas as pd
import script
#import dscript
import high_confident
import D_extract
import error_correction
import io
import cdr3
import cdr1_cdr2
import tempfile
import subprocess
import os
import math
import novel
#need to install 'pip install biopython' to run import blast

def main():
    # your existing code here
    print("VDJcraft is running")

if __name__ == "__main__":
    main()


script_dir = os.path.dirname(os.path.abspath(__file__))
# Paths to BED files inside your tool folder
hs38_bed = os.path.join(script_dir, "VDJC_hg38_CDSuniq.bed")
hs37_bed = os.path.join(script_dir, "hg37_VDJ_CDSgenome.bed")
Mm_bed = os.path.join(script_dir, "Mm39_VDJ_CDSgenome.bed")
t2t_bed = os.path.join(script_dir, "T2T_VDJ_CDSgenome.bed")
CDR2_consensus = os.path.join(script_dir, "CDR2.consensus.csv")
#IMGT_ref = os.path.join(script_dir, "IMGT_ref/IMGT_VJC")
#IMGT_D = os.path.join(script_dir, "IMGT_Dref/IMGT_D.new")

parser = argparse.ArgumentParser(description="blastn")

#set up the blastn command line
group = parser.add_mutually_exclusive_group(required=True)
group1 = parser.add_mutually_exclusive_group()
group.add_argument('-I','--fastq', type=str, help="Enter your input file")
group.add_argument('-bam','--bamin', type=str, help="input bam alignment file")
group.add_argument('-ont','--ontfq', type=str, help="Enter your input ONT file")
group1.add_argument('-t2t', '-t2t', action="store_true", help="Use T2T BED file")
group1.add_argument('-hs37', '-hs37',action="store_true", help="Use hs37 BED file")
group1.add_argument('-Mm', '-Mm', action="store_true", help="Use Mm BED file")
parser.add_argument('-R','--database', type=str, help="Enter your database")
parser.add_argument('-ref','--ref', type=str, help="Enter your human reference genome")
parser.add_argument('-O', '--outs', type=str, help="Set output folder",required=True)
parser.add_argument('-of','--outfile',type=str, help="output result file",required=True)
parser.add_argument('-p', '--VJIdent', type=int, default = 90, help="Enter preferred identifation percentage for VJ genes")
parser.add_argument('-pd', '--DIdent', type=int, default = 95, help="Enter preferred identifation percentage for D genes")
parser.add_argument('-s', '--score', type=int, default = 300, help="Enter preferred matching score")
parser.add_argument('-shm', '--shm', action="store_true", help="Enter to get novel events due to SHM")
parser.add_argument('-m', '--mpct', type=int, default = 85, help="Enter cutoff of matching rate for SHM")


args = parser.parse_args()

if not args.bamin and not args.ref:
    parser.error("You must provide --ref when FASTQ input is used. (--bam does not require reference)")

if args.Mm:
    IMGT_ref = os.path.join(script_dir, "Mm_IMGT_ref/Mm_IMGT_VJC")
    IMGT_D = os.path.join(script_dir, "Mm_IMGT_Dref/Mm_IMGT_D")
else:
    IMGT_ref = os.path.join(script_dir, "IMGT_ref/IMGT_VJC")
    IMGT_D = os.path.join(script_dir, "IMGT_Dref/IMGT_D.new")

output_folder = args.outs
def generate_output_file(file_name):
    os.makedirs(output_folder, exist_ok=True)  # ensure folder exists
    return os.path.join(output_folder, file_name)


in_file = args.fastq
ont_file=args.ontfq
temp = "temp_folder"
temp_dir = generate_output_file(temp)
os.makedirs(temp_dir, exist_ok=True)

minimap2_output_file = os.path.join(temp_dir, 'minimap2_output.sam')
if args.bamin:
    samtools_bam_file = args.bamin
else:
    if args.ontfq:
        minimap2_cmd = ['minimap2', '-t 8', '-ax', 'splice', args.ref, ont_file]
    else:
        minimap2_cmd = ['minimap2', '-ax', 'splice:hq', '-uf', args.ref, in_file]
#minimap2_cmd = ['minimap2', '-t 8', '-ax', 'splice:hq', '-uf', '/data/scratch/klhu0502/raw_data/GRCh38_full_analysis_set_plus_decoy_hla.fa', in_file]
#minimap2_cmd = ['minimap2', '-t 8', '-ax', 'splice','/data/scratch/klhu0502/raw_data/GRCh38_full_analysis_set_plus_decoy_hla.fa', ont_file]

    with open(minimap2_output_file, 'w') as minimap2_output:
        minimap2_proc = subprocess.run(minimap2_cmd, stdout=minimap2_output, check=True)

    samtools_bam_file = os.path.join(temp_dir, 'samtools_output.bam')
    samtools_cmd = ['samtools', 'view', '-b', minimap2_output_file]
    with open(samtools_bam_file, 'wb') as samtools_bam_output:
        samtools_proc = subprocess.run(samtools_cmd, stdout=samtools_bam_output)    

#if args.bamin:
#    bam_file = args.bamin
#else:
#    bam_file = sorted_bam_file

sorted_bam_file = os.path.join(temp_dir, 'sorted_output.bam')
samtools_cmd_sort = ['samtools', 'sort', samtools_bam_file]
with open(sorted_bam_file, 'wb') as sorted_bam_output:
    samtools_proc_sort = subprocess.run(samtools_cmd_sort, stdout=sorted_bam_output)

samtools_index_file = sorted_bam_file + '.bai'
samtools_cmd_index = ['samtools', 'index', sorted_bam_file]
samtools_proc_index = subprocess.run(samtools_cmd_index)

index_file_destination = os.path.join(temp_dir, os.path.basename(samtools_index_file))
shutil.move(samtools_index_file, index_file_destination)

if args.t2t:
    bed_file = t2t_bed
elif args.Mm:
    bed_file = Mm_bed
elif args.hs37:
    bed_file = hs37_bed
else:
    bed_file = hs38_bed

#/data/user/klhu0502/work/longscript/vdjtool/VDJC_genome_CDSuniq.bed
samtools_vdj_bam = os.path.join(temp_dir, 'samtools_vdj.bam')
samtools_cmd3 = ['samtools', 'view', '-b', '-L', bed_file, sorted_bam_file]
with open(samtools_vdj_bam, 'wb') as vdj_bam:
    samtools_proc_vdj = subprocess.run(samtools_cmd3, stdout=vdj_bam)

samtools_cmd_view = ['samtools', 'view', samtools_vdj_bam]
samtools_proc_view = subprocess.run(samtools_cmd_view, stdout=subprocess.PIPE)
cut_cmd = ['cut', '-f', '1,3,4']
cut_proc = subprocess.run(cut_cmd, input=samtools_proc_view.stdout, stdout=subprocess.PIPE)
columns = ['Query', 'chr', 'position']
pos_df = pd.read_csv(io.StringIO(cut_proc.stdout.decode()), sep='\t', header=None, names=columns)

table ='table.csv'
tablefile=generate_output_file(table)
with open (tablefile, 'w') as c:
    pos_df.to_csv(c, sep='\t', index=False, na_rep='NA')

#file_path ='/data/user/klhu0502/work/longscript/vdjtool/test/vdj_candidate.fa'
output_file = 'vdj_candidate.fa'
file_path=generate_output_file(output_file)
samtools_cmd5 = ['samtools', 'fasta', '-F', '4', samtools_vdj_bam]
with open (file_path, 'w') as k:
    subprocess.run(samtools_cmd5, stdout=k, check=True)


shutil.rmtree(temp_dir)

#dseq_file ='/data/user/klhu0502/work/longscript/dseq.fa'
def extract_sequences(fasta_file, queries_df, dseq_file):
    queries = {}
    for _, row in queries_df.iterrows():
        queries[row['Query']] = (row['dstart'], row['dend'])
    sequences = {}
    with open(fasta_file, 'r') as infile, open(dseq_file, 'w') as outfile:
        sequence = ""
        current_query = ""

        for line in infile:
            if line.startswith('>'):
                if current_query in queries:
                    start, end = queries[current_query]
                    if not (math.isnan(start) or math.isnan(end)):
                         start = int(start)
                         end = int(end)
                         if start >= 1 and start < end:
                               outfile.write(f">{current_query}\n{sequence[start-1:end]}\n")
                current_query = line.strip()[1:]
                sequence = ""
            else:
                sequence += line.strip()

        # Process the last sequence after the loop ends
        if current_query in queries:
            start, end = queries[current_query]
            if not (math.isnan(start) or math.isnan(end)):
                start = int(start)
                end = int(end)
                if start >= 1 and start < end:
                       outfile.write(f">{current_query}\n{sequence[start-1:end]}\n")
 #   return outfile
##just need this part.
blastout = "blastout.txt"
file_blast=generate_output_file(blastout)
if os.path.exists(file_blast):
    os.remove(file_blast)


blastn_cmd = ['blastn','-query',file_path,'-db',IMGT_ref,'-out',file_blast]
subprocess.run(blastn_cmd)


output_file = "raw_gene.txt"
raw=generate_output_file(output_file)
if os.path.exists(raw):
    os.remove(raw)

with open(file_blast, 'r') as f:
    script.blastfmt(f,raw)

f.close()

addline='addline.csv'
add_line=generate_output_file(addline)
vdjout="vdjout.csv"
vdjc_out=generate_output_file(vdjout)
vjfile="vjtemp.csv"
vjtemp=generate_output_file(vjfile)
vgene="vgene.csv"
vgene_temp=generate_output_file(vgene)
VJIdent = args.VJIdent
high_confident.top_extract(raw,add_line,vdjc_out,vjtemp,vgene_temp,VJIdent)


dseq_file ='dgene_candidate.fa'
file_dseq =generate_output_file(dseq_file)

blastoutd = "blastoutd.txt"
file_blastd=generate_output_file(blastoutd)
if os.path.exists(file_blastd):
   os.remove(file_blastd)

#/data/user/klhu0502/work/longscript/dgenedb/IMGTD.fa
with open(vjtemp,'r') as vj:
    bed_vj=pd.read_csv(vjtemp, sep='\t', header=0)
    bed_vj['dstart'] = bed_vj.apply(lambda row: row['v_queryend']-20 if row['strand'] == 'Plus/Plus' else row['j_queryend']-20, axis=1)
    bed_vj['dend'] = bed_vj.apply(lambda row: row['j_querystart']+20 if row['strand'] == 'Plus/Plus' else row['v_querystart']+20, axis=1)
#    bed_fullvdj['start'] = bed_fullvdj.apply(lambda row: row['v_querystart'] if row['strand'] == 'Plus/Plus' else row['j_queryend'], axis=1)
#    bed_fullvdj['end'] = bed_fullvdj.apply(lambda row: row['j_queryend'] if row['strand'] == 'Plus/Plus' else row['v_querystart'], axis=1)
    extracted_sequences = D_extract.extract_sequences(file_path, bed_vj, file_dseq)
    blastn_d = ['blastn','-query',file_dseq,'-db',IMGT_D, '-word_size','7','-evalue','0.05','-out',file_blastd]
    subprocess.run(blastn_d)

vj.close()

output_filename = "raw_dgene.txt"
rawd=generate_output_file(output_filename)

#with open(file_blastd, 'r') as d:
#    dscript.blastdgene(d,rawd)

with open(file_blastd, 'r') as d:
    script.blastfmt(d,rawd)

dout="top_dgene.csv"
d_out=generate_output_file(dout)
DIdent = args.DIdent
D_extract.top_extract(rawd,d_out,DIdent)


orig_vdj = "vdjc_original.csv"
mergevdjc= generate_output_file(orig_vdj)

with open(vdjc_out,'r') as vjc, open(d_out,'r') as d:

    df_vjc = pd.read_csv(vjc, sep='\t', header=0)

    df_d = pd.read_csv(d, sep='\t', header=0)

    df_vjc = df_vjc.dropna(subset=['Query']).drop_duplicates(subset='Query', keep='first')

    df_d = df_d.dropna(subset=['Query']).drop_duplicates(subset='Query', keep='first')

    merge_vdjc = pd.merge(df_vjc, df_d, on = 'Query', how='outer')

    merge_vdjc = merge_vdjc[['v_gene','d_gene','j_gene','c_gene','v_seq','d_seq','j_seq','Query']]

#    merge_vdjc.loc[merge_vdjc['v_gene'].str.contains('IGKV|IGLV|TRAV|TRGV', regex=True), 'd_gene'] = '.'

#    sort_vdjc = merge_vdjc.iloc[1:].sort_values(by=merge_vdjc.columns[0])

    merge_vdjc.to_csv(mergevdjc, sep='\t', index=False, na_rep='.')

vjc.close()
d.close()

corr_vdjc = "vdjc_corrected.csv"
correct_vdjc = generate_output_file(corr_vdjc)
with open(mergevdjc,'r') as vdjc, open(tablefile,'r') as T:
    df_vdjc = pd.read_csv(vdjc, sep='\t', header=0)

    df_pos = pd.read_csv(T, sep='\t', header=0)

    pos_vdjc = pd.merge(df_pos, df_vdjc, on = 'Query', how='inner')

    corrected_df = error_correction.error_correction(pos_vdjc)

    sorted_df = corrected_df.iloc[1:].sort_values(by=corrected_df.columns[0])

    sorted_df.to_csv(correct_vdjc, sep='\t', index=False, na_rep='.')

T.close()

cdr3_file = "cdr3.csv"
cdr3_bed = "cdr3.bed"
cdr3_temp = generate_output_file(cdr3_file)
bed_temp = generate_output_file(cdr3_bed)
cdr3.cdr3_extract(vjtemp, file_path, bed_temp, cdr3_temp)



def add_count_column(df, sort_by_count=True):
    cols = ['v_gene', 'd_gene', 'j_gene', 'c_gene', 'cdr_sequence', 'aa_sequence', 'Query']
    
    grouped = df.groupby(cols).size().reset_index(name='count')
    
    
    reordered_cols = ['count'] + [col for col in cols if col != 'Query'] + ['Query']
    grouped = grouped[reordered_cols]
    
    
    if sort_by_count:
        grouped = grouped.sort_values(by='count', ascending=False).reset_index(drop=True)
    
    return grouped


vdj_report = "vdjcraft_report.csv"
final_vdjc = generate_output_file(vdj_report)
with open(correct_vdjc,'r') as allvdj, open(cdr3_temp,'r') as cdr:
    df_allvdj = pd.read_csv(allvdj, sep='\t', header=0)

    df_cdr = pd.read_csv(cdr, sep='\t', header=0)

    df_final = pd.merge(df_allvdj, df_cdr, on = 'Query', how='left')

    df_final = df_final[['Query', 'v_gene', 'd_gene', 'j_gene', 'c_gene', 'cdr_sequence', 'aa_sequence']]

    result_df = add_count_column(df_final)

    result_df.to_csv(final_vdjc, sep='\t', index=False, na_rep='out_of_frame')


cdr1 = "cdr1.csv"
cdr1_temp = generate_output_file(cdr1)
cdr2 = "cdr2.csv"
cdr2_temp = generate_output_file(cdr2)
dfcdr2_temp = "dfcdr2_temp.csv"
dfcdr2 = generate_output_file(dfcdr2_temp)
with open(vgene_temp,'r') as cd:
    df_v = pd.read_csv(cd, sep='\t', header=0)
    cdr1 = cdr1_cdr2.extract_cdr1_sequence(df_v)
    cdr1.to_csv(cdr1_temp, sep='\t', index=False, na_rep='out_of_frame')
    df2=pd.read_csv(CDR2_consensus, sep='\t',header=0)
    #*mergecdr2 = pd.merge(merge_vdjc, df2, on = 'v_gene')
    df_v['v_gene'] = df_v['v_gene'].str.replace(r'_.*', '', regex=True)
    df_cdr2 = pd.merge(df_v, df2, on = 'v_gene', how='inner')
    df_cdr2.to_csv(dfcdr2, sep='\t', index=False, na_rep='out_of_frame')
    if df_cdr2.empty:
        print("Merge resulted in an empty DataFrame. Skipping CDR2 extraction.")
    else:
    # Extract CDR2 if the DataFrame is not empty
        cdr2 = cdr1_cdr2.cdr2_extract(df_cdr2, 'v_gene', 'strand', 'v_seq', 'cdr2seq', 'cdr2_rev', 'Query')
        cdr2.to_csv(cdr2_temp, sep='\t', index=False, na_rep='out_of_frame')


#Add function for potential novel events for Somatic hypermutation.
def SHM_event(df, sort_by_count=True):
    cols = ['Gene', 'queryseq']

    grouped = df.groupby(cols).size().reset_index(name='count')

    reordered_cols = ['count'] + cols
    grouped = grouped[reordered_cols]

    if sort_by_count:
        grouped = grouped.sort_values(by='count', ascending=False).reset_index(drop=True)

    return grouped



if args.shm:
    output_vj = 'output_vj.txt'
    vj = generate_output_file(output_vj)
    novel_temp = "novel.csv"
    shm_temp = generate_output_file(novel_temp)
    novel.top_extract(raw, vj)
    with open(vj,'r') as vj_temp:
        df_shm = pd.read_csv(vj_temp, sep='\t', header=0)
        df_shm = df_shm[['Query', 'Gene','Iden_percentage','queryseq']]
        df_shm['Iden_percentage_float'] = df_shm['Iden_percentage'].str.rstrip('%').astype(float)
        filtered_df_shm = df_shm[df_shm['Iden_percentage_float'] < args.mpct]
        df_shm_select = filtered_df_shm[['Gene','queryseq']]
        result_shm = SHM_event(df_shm_select)
        result_shm.to_csv(shm_temp, sep='\t', index=False, na_rep='out_of_frame')


